options:
  config-file: node_modules/tjw-sasslint-rules/tjwsasslint.yml
files:
  include: 'scout-files/_sass/**/*.s+(a|c)ss'
  ignore:
    - 'scout-files/_sass/ven.bootstrap/**/*'
    - 'scout-files/_sass/ven.bootswatch/**/*'
